# Site settings
title: "Minnesota Extensible Language Tools"
description: "Programming languages research group at the University of Minnesota - Twin Cities. Research focuses on composable language extensions. Copper, Silver, AbleC."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://melt.cs.umn.edu" # the base hostname & protocol for your site
lang: "en"
strict_front_matter: true
timezone: "America/Chicago"

sv_wiki_base: "" # path from domain root to the silver wiki, used to emit "wiki links"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
# GFM is necessary to understand triple backticks-style code blocks "Github Flavored Markdown"
  hard_wrap: false

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - menu-builder.py
  - .gitignore
  - jenkins
  - Jenkinsfile

