# Site settings
title: "Minnesota Extensible Language Tools"
description: "Programming languages research group at the University of Minnesota - Twin Cities. Research focuses on composable language extensions. Copper, Silver, AbleC."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://melt.cs.umn.edu" # the base hostname & protocol for your site
lang: "en"
strict_front_matter: true
timezone: "America/Chicago"

# Tell Jekyll to pay attention to what's in _pages
collections:
  pages:
    output: true

# Tell Jekyll some default values for what's in _pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: sv_wiki

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - .gitignore
  - Jenkinsfile
  - Makefile

