#!/bin/bash

set -eu

if [ $0 != "./gen-docs" ]; then
  echo "Run as ./gen-docs"
  exit 1
fi

ORIG=$(pwd)
: ${SVWORKSPACE=/export/scratch/melt-jenkins/custom-silver}
SV=gendoc_scratch

if [ ! -d "$SVWORKSPACE" ]; then
  echo "$SVWORKSPACE not found (default is for coldpress)"
  exit 1
fi

if [ -d "$SV" ]; then
  rm -rf "$SV"
fi

mkdir -p "$SV"

cp -r "$SVWORKSPACE"/* "$SV"

cd "$SV"

if [ -d "generated" ]; then
	rm -rf generated
fi

# Run silver to generate some docs
mkdir -p generated

./support/bin/silver --dont-translate --doc --clean silver:compiler:extension:doc:extra

rm ./build.xml

mkdir -p "$ORIG/silver/gen/"
rm -rf "$ORIG/content/silver/gen/*"
git checkout -- "$ORIG/content/silver/gen/_index.md" #sorry
cp -r generated/doc/* "$ORIG/content/silver/gen/"


